### ISSUE TITLE
Documentation for some queries.

### ISSUE THREAD

**Issue by skroo** [tntwebsolutions/ts3query#4]
I love that this exists, it should make my life scripting teamspeak tasks much easier. I'm having trouble figuring out how I should form some of the commands. It looks like they might not be implemented, but I want to make sure I'm just not doing it wrong. For example, I want to use "clientdbfind." This has the parameter "pattern" that has to be passed and the option "uid" that I want to also pass. It appears from your documentation that I should use:

```
@query.clientdbfind :pattern => "tsuid string" do |opt|
     opt.uid
end
```

It seems some commands like "clientdbfind" throw an error because the script is waiting for something else. I can't find a pattern to why some commands work and others don't.

```
Net::ReadTimeout: timed out while waiting for more data
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/telnet.rb:557:in `waitfor'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/telnet.rb:694:in `cmd'
    from /Library/Ruby/Gems/2.0.0/gems/ts3query-0.7.0/lib/ts3query/ts3_connection.rb:38:in `method_missing'

```

**Comment by skroo** [comment]
I think the issue is when you run a command that doesn't return a list delimited with the '|' character. Things work fine when TS returns one of its goofy pipe delimited lists, but if it returns data with no pipe character, it hangs. Since 'clientdbfind' only returns "cldbid=173637" there's no pipe. It also explains why you can't use this to send commands to the server.

I'm not positive that this is what is going on but it's the best I can come up with. I'm kind of a newb.
